// Phase 4G/4H — native-owned frontend settings persistence.
//
// EVIDENCE (instruction-level, original binary — see
// docs/ENGINE_RECONSTRUCTION.md Phases 4G/4H and
// analysis-private/logs/decomp_25de4.txt, decomp_4260ac.txt,
// disasm_4260ac_full.txt, disasm_20d68.txt):
//
//   Reader FUN_00425de4 (runs once at WinMain startup, OBSERVED):
//     copies the 670-byte factory-defaults block DAT_0049afe4 ->
//     live block DAT_005411f0, then applies `name = value` lines
//     from the resolved config through the 92-entry
//     {name,type,value_ptr} table at 0x49aca8. Key match is
//     FUN_0042fab4 — ASCII fold (`and 0xdf`) case-insensitive
//     compare. Per-type value parse (OBSERVED): types 0/4 ->
//     strtol-family int; type 1 -> atof; type 2 -> toupper of the
//     first value char == 'T' (FUN_0047d1a5 + `cmp 0x54`); type 3 ->
//     string copy.
//
//   Writer FUN_004260ac (called from FUN_00420d68 iff
//   DAT_00541486 != 0, OBSERVED):
//     emits `; MDK Configuration file automatically generated by
//     MDK` + blank line, then `name = value` per table entry ONLY
//     for values that differ from the defaults mirror
//     (*value_ptr != *(value_ptr - 0xa620c)), in table order.
//     Formats: int `%s = %d`, bool `%s = TRUE`/`%s = FALSE`,
//     string `%s = %s`, float `%s = %g`, hex `%s = 0x%X`.
//
//   This module reproduces that contract for the five proven
//   entries only — deliberately not a general settings framework:
//     entry 8  SoundFX       int  DAT_00541308  factory 70 (@0x49b0fc)
//     entry 9  SoundMusic    int  DAT_0054130c  factory 100 (@0x49b100)
//     entry 88 Skill         int  DAT_0054147a  factory 1 (@0x49b26e)
//     entry 89 Brightness    int  DAT_0054147e  factory 0 (@0x49b272)
//     entry 90 ForcePCorrect bool DAT_00541482  factory FALSE (@0x49b276)
//   (Phase 4I adds entries 8/9 — the Sound screen's volume globals.
//   Table order places them BEFORE Skill: the writer emits a dirty
//   file with the SoundFX/SoundMusic lines first.)
//   The file is written through the native-owned seam below, never
//   inside the read-only DataRoot (the original's MDK.CFG paths are
//   NOT reproduced: `original/installed/MDK.CFG` and anything under
//   the data root stay untouched).
//
#ifndef MDK_CORE_FRONTEND_SETTINGS_H
#define MDK_CORE_FRONTEND_SETTINGS_H

#include <filesystem>
#include <optional>
#include <string>
#include <string_view>

namespace mdk {

// Persisted frontend settings — the five proven table entries:
// DAT_00541308 SoundFX (sound row-0 domain [0,100] step 10,
// factory 70), DAT_0054130c SoundMusic (row-1, factory 100),
// DAT_0054147a skill (domain [0,2], factory 1 = "Skill - Normal"),
// DAT_0054147e brightness (display row-0 domain [0,7], factory 0),
// DAT_00541482 ForcePCorrect (type-2 bool, factory FALSE).
// Field order below keeps the 4G/4H members first so existing
// positional `FrontendSettings{skill}` initializers keep their
// meaning; the SERIALIZER emits in original table order
// (SoundFX, SoundMusic, Skill, Brightness, ForcePCorrect).
struct FrontendSettings {
  int skill = 1;
  int brightness = 0;
  bool forcePCorrect = false;
  int soundFx = 70;
  int soundMusic = 100;
};

inline constexpr int kFrontendSkillDefault = 1;       // @0x49b26e
inline constexpr int kFrontendSkillMin = 0;           // OBSERVED domain
inline constexpr int kFrontendSkillMax = 2;           //   0..2
inline constexpr int kFrontendBrightnessDefault = 0;  // @0x49b272
inline constexpr int kFrontendBrightnessMin = 0;      // OBSERVED row-0
inline constexpr int kFrontendBrightnessMax = 7;      //   domain 0..7
inline constexpr int kFrontendSoundFxDefault = 70;    // @0x49b0fc
inline constexpr int kFrontendSoundMusicDefault = 100;// @0x49b100
inline constexpr int kFrontendSoundVolumeMin = 0;     // OBSERVED rows
inline constexpr int kFrontendSoundVolumeMax = 100;   //   0..100

// OBSERVED file head (`;` comment line + blank line, "\n\n" in the
// original's text-mode write -> CRLF pairs on disk in BUILD_A).
// Reproduced verbatim as the proven format marker — the file stays
// a well-formed MDK.CFG for the future full-table writer.
inline constexpr std::string_view kFrontendSettingsHeader =
    "; MDK Configuration file automatically generated by MDK";

// FUN_004260ac's emission contract for the five proven entries
// (OBSERVED): header + blank line, then non-default values in
// table order — `SoundFX = %d` iff != 70, `SoundMusic = %d` iff
// != 100, `Skill = %d` iff != 1, `Brightness = %d` iff != 0,
// `ForcePCorrect = TRUE` iff != FALSE (the writer emits a value
// only when the live dword differs from the mirror, so FALSE is
// never emitted for the proven bool). Lines terminate CRLF —
// BUILD_A's on-disk MDK.CFG is a DOS text file; matching its line
// endings keeps written files byte-true to the proven format
// rather than host-dependent.
std::string serializeFrontendSettings(const FrontendSettings& s);

// FUN_00425de4's load contract for the five proven entries:
// start from the factory defaults, apply `name = value` lines in
// order (the last valid line for each key wins). `;`-led lines
// and lines without a valid `name = value` shape are skipped like
// the original's parser.
//
// NATIVE POLICY — hardening, NOT an original-behavior claim: a
// `Skill`/`Brightness`/`SoundFX`/`SoundMusic` line whose value
// fails integer parse or falls outside the proven domain
// ([0,2] / [0,7] / [0,100]) is ignored (the running value is
// kept) and counted. The original stores whatever its strtol-style
// parse yields — that edge behavior is UNKNOWN and deliberately
// not reproduced. `ForcePCorrect` is type 2: the original applies
// it unconditionally as toupper(first value char) == 'T'
// (FUN_0047d1a5 + `cmp 0x54`) — reproduced exactly, never
// counted as ignored.
struct FrontendSettingsParse {
  FrontendSettings settings;
  int ignoredSkillLines = 0;
  int ignoredBrightnessLines = 0;
  int ignoredSoundFxLines = 0;
  int ignoredSoundMusicLines = 0;
};
FrontendSettingsParse parseFrontendSettings(std::string_view text);

// Native-owned file seam — the only frontend-settings I/O in the
// port. `path` is always caller-supplied and must live OUTSIDE the
// read-only DataRoot (enforced by the caller/app layer — this
// module holds no data-root reference at all).
//
// load: nullopt when the file is absent (fresh-boot case — not an
// error); fills `err` and returns nullopt on a real read failure.
// save: false + `err` on any open/write failure — the caller
// decides the failure policy (the flow mirrors the original's
// unconditional dirty-flag clear even on write failure).
std::optional<FrontendSettingsParse> loadFrontendSettingsFile(
    const std::filesystem::path& path, std::string* err = nullptr);
bool saveFrontendSettingsFile(const std::filesystem::path& path,
                              const FrontendSettings& s,
                              std::string* err = nullptr);

} // namespace mdk

#endif // MDK_CORE_FRONTEND_SETTINGS_H
