// Phase 4G — native-owned frontend settings persistence (Skill only).
//
// EVIDENCE (instruction-level, original binary — see
// docs/ENGINE_RECONSTRUCTION.md Phase 4G and
// analysis-private/logs/decomp_25de4.txt, decomp_4260ac.txt,
// disasm_4260ac_full.txt, disasm_20d68.txt):
//
//   Reader FUN_00425de4 (runs once at WinMain startup, OBSERVED):
//     copies the 670-byte factory-defaults block DAT_0049afe4 ->
//     live block DAT_005411f0, then applies `name = value` lines
//     from the resolved config through the 92-entry
//     {name,type,value_ptr} table at 0x49aca8. Key match is
//     FUN_0042fab4 — ASCII fold (`and 0xdf`) case-insensitive
//     compare.
//
//   Writer FUN_004260ac (called from FUN_00420d68 iff
//   DAT_00541486 != 0, OBSERVED):
//     emits `; MDK Configuration file automatically generated by
//     MDK` + blank line, then `name = value` per table entry ONLY
//     for values that differ from the defaults mirror. Skill is
//     entry 88: name "Skill", int `%s = %d`, live ptr
//     &DAT_0054147a, factory default 1 — serialized iff != 1.
//
//   This module reproduces that contract for the Skill entry ONLY
//   — deliberately not a general settings framework. The file is
//   written through the native-owned seam below, never inside the
//   read-only DataRoot (the original's MDK.CFG paths are NOT
//   reproduced: `original/installed/MDK.CFG` and anything under
//   the data root stay untouched).
//
#ifndef MDK_CORE_FRONTEND_SETTINGS_H
#define MDK_CORE_FRONTEND_SETTINGS_H

#include <filesystem>
#include <optional>
#include <string>
#include <string_view>

namespace mdk {

// Persisted frontend settings — Phase 4G scope is the single
// proven entry: DAT_0054147a skill, domain [0,2], factory
// default 1 ("Skill - Normal").
struct FrontendSettings {
  int skill = 1;
};

inline constexpr int kFrontendSkillDefault = 1;   // mirror @0x49b26e
inline constexpr int kFrontendSkillMin = 0;       // OBSERVED domain
inline constexpr int kFrontendSkillMax = 2;       //   0..2

// OBSERVED file head (`;` comment line + blank line, "\n\n" in the
// original's text-mode write -> CRLF pairs on disk in BUILD_A).
// Reproduced verbatim as the proven format marker — the file stays
// a well-formed MDK.CFG for the future full-table writer.
inline constexpr std::string_view kFrontendSettingsHeader =
    "; MDK Configuration file automatically generated by MDK";

// FUN_004260ac's emission contract, Skill entry only (OBSERVED):
// header + blank line, then `Skill = %d` iff skill != default.
// Lines terminate CRLF — BUILD_A's on-disk MDK.CFG is a DOS text
// file; matching its line endings keeps written files byte-true
// to the proven format rather than host-dependent.
std::string serializeFrontendSettings(const FrontendSettings& s);

// FUN_00425de4's load contract, Skill entry only: start from the
// factory defaults, apply `name = value` lines in order (the last
// valid Skill line wins). `;`-led lines and lines without a valid
// `name = value` shape are skipped like the original's parser.
//
// NATIVE POLICY — hardening, NOT an original-behavior claim: a
// `Skill` line whose value fails integer parse or falls outside
// the proven [0,2] domain is ignored (the running value is kept)
// and counted in `ignoredSkillLines`. The original stores whatever
// its strtol-style parse yields — that edge behavior is UNKNOWN
// and deliberately not reproduced.
struct FrontendSettingsParse {
  FrontendSettings settings;
  int ignoredSkillLines = 0;
};
FrontendSettingsParse parseFrontendSettings(std::string_view text);

// Native-owned file seam — the only frontend-settings I/O in the
// port. `path` is always caller-supplied and must live OUTSIDE the
// read-only DataRoot (enforced by the caller/app layer — this
// module holds no data-root reference at all).
//
// load: nullopt when the file is absent (fresh-boot case — not an
// error); fills `err` and returns nullopt on a real read failure.
// save: false + `err` on any open/write failure — the caller
// decides the failure policy (the flow mirrors the original's
// unconditional dirty-flag clear even on write failure).
std::optional<FrontendSettingsParse> loadFrontendSettingsFile(
    const std::filesystem::path& path, std::string* err = nullptr);
bool saveFrontendSettingsFile(const std::filesystem::path& path,
                              const FrontendSettings& s,
                              std::string* err = nullptr);

} // namespace mdk

#endif // MDK_CORE_FRONTEND_SETTINGS_H
