// Phase 4G/4H — native-owned frontend settings persistence.
//
// EVIDENCE (instruction-level, original binary — see
// docs/ENGINE_RECONSTRUCTION.md Phases 4G/4H and
// analysis-private/logs/decomp_25de4.txt, decomp_4260ac.txt,
// disasm_4260ac_full.txt, disasm_20d68.txt):
//
//   Reader FUN_00425de4 (runs once at WinMain startup, OBSERVED):
//     copies the 670-byte factory-defaults block DAT_0049afe4 ->
//     live block DAT_005411f0, then applies `name = value` lines
//     from the resolved config through the 92-entry
//     {name,type,value_ptr} table at 0x49aca8. Key match is
//     FUN_0042fab4 — ASCII fold (`and 0xdf`) case-insensitive
//     compare. Per-type value parse (OBSERVED): types 0/4 ->
//     strtol-family int; type 1 -> atof; type 2 -> toupper of the
//     first value char == 'T' (FUN_0047d1a5 + `cmp 0x54`); type 3 ->
//     string copy.
//
//   Writer FUN_004260ac (called from FUN_00420d68 iff
//   DAT_00541486 != 0, OBSERVED):
//     emits `; MDK Configuration file automatically generated by
//     MDK` + blank line, then `name = value` per table entry ONLY
//     for values that differ from the defaults mirror
//     (*value_ptr != *(value_ptr - 0xa620c)), in table order.
//     Formats: int `%s = %d`, bool `%s = TRUE`/`%s = FALSE`,
//     string `%s = %s`, float `%s = %g`, hex `%s = 0x%X`.
//
//   This module reproduces that contract for the proven entries
//   only — deliberately not a general settings framework:
//     entry 8  SoundFX       int  DAT_00541308  factory 70 (@0x49b0fc)
//     entry 9  SoundMusic    int  DAT_0054130c  factory 100 (@0x49b100)
//     entry 88 Skill         int  DAT_0054147a  factory 1 (@0x49b26e)
//     entry 89 Brightness    int  DAT_0054147e  factory 0 (@0x49b272)
//     entry 90 ForcePCorrect bool DAT_00541482  factory FALSE (@0x49b276)
//   (Phase 4I adds entries 8/9 — the Sound screen's volume globals.
//   Table order places them BEFORE Skill: the writer emits a dirty
//   file with the SoundFX/SoundMusic lines first.)
//
//   Phase 4J adds the proven Mouse block, entries 49-68 (the Mouse
//   screen mutates the W set; the D set is persisted so a dirty
//   rewrite doesn't lose proven non-default lines like BUILD_A's
//   `MouseDButtMapD = 32768`):
//     49 MouseWAxesMap   type-3 char[4]  DAT_005413de  "ABG"
//     50 MouseDAxesMap   type-3 char[4]  DAT_005413e2  "ABG"
//     51 MouseWButtMap   type-3 char[5]  DAT_005413b4  "ACB"
//     52 MouseDButtMap   type-3 char[5]  DAT_005413b9  "ACB"
//     53-56 MouseWButtMapA..D type-0 dword DAT_005413be..ca {1,4,2,0}
//     57-60 MouseDButtMapA..D type-0 dword DAT_005413ce..da {1,4,2,0}
//     61-63 MouseWX/Y/ZScale   type-1 float DAT_005413e6..ee {16,16,50}
//     64-66 MouseDX/Y/ZScale   type-1 float DAT_005413f2..fa {16,16,50}
//     67 MouseOn         type-2 bool DAT_00541472  factory TRUE
//     68 MouseYReversed  type-1 float DAT_00541476  factory 0.0f —
//        the screen writes raw int32 0/1 into the float slot
//        (OBSERVED quirk — a toggled-on value serializes as
//        `MouseYReversed = 1.4013e-45`, the denormal for bits 1);
//        the port stores the raw dword bits.
//   Emission order is the table order: entries 49-68 sit between
//   SoundMusic (9) and Skill (88).
//   The file is written through the native-owned seam below, never
//   inside the read-only DataRoot (the original's MDK.CFG paths are
//   NOT reproduced: `original/installed/MDK.CFG` and anything under
//   the data root stay untouched).
//
//   Phase 4K adds the proven Keyboard block — settings-table
//   entries 69-87, all type-0 dword slots holding ORIGINAL internal
//   key codes (0..127, NOT SDL scancodes — the domain is preserved,
//   not translated):
//     69 KeyLeft      DAT_005413fe  factory 105 (UP-arrow ext code)
//     70 KeyRight     DAT_00541402  factory 106
//     71 KeyUp        DAT_00541406  factory 103
//     72 KeyDown      DAT_0054140a  factory 108
//     73 KeyJump      DAT_0054140e  factory 56  (LALT)
//     74 KeySide      DAT_00541412  factory 45  ('X')
//     75 KeyFire      DAT_00541416  factory 29  (LCTRL)
//     76 KeySniper    DAT_0054141a  factory 57  (SPACE)
//     77 KeyTurbo     DAT_0054141e  factory 42  (LSHIFT)
//     78 KeySturbo    DAT_00541422  factory 58  (CAPS)
//     79 KeyLookUp    DAT_00541426  factory 30  ('A')
//     80 KeyLookDown  DAT_0054142a  factory 44  ('Z')
//     81 KeyZoomIn    DAT_0054142e  factory 30  ('A' — factory dup)
//     82 KeyZoomOut   DAT_00541432  factory 44  ('Z' — factory dup)
//     83 KeyItemNext  DAT_0054145e  factory 27  (']')
//     84 KeyItemPrev  DAT_00541462  factory 26  ('[')
//     85 KeyItemUse   DAT_00541466  factory 28  (RETURN)
//     86 KeySideL     DAT_0054146a  factory 51  (',')
//     87 KeySideR     DAT_0054146e  factory 52  ('.')
//   Entries 69-87 emit between MouseYReversed (68) and Skill (88) —
//   each iff its value differs from the mirror (BUILD_A's MDK.CFG
//   carries no Key* lines: all bindings sit at factory defaults).
//   The ten hidden hotkey globals between KeyZoomOut (0x541432) and
//   KeyItemNext (0x54145e) — 0x541436..0x54145a, factory 2..11 —
//   share the same reset block but are NOT table entries: never
//   read, never written, never shown.
//
#ifndef MDK_CORE_FRONTEND_SETTINGS_H
#define MDK_CORE_FRONTEND_SETTINGS_H

#include <cstdint>
#include <filesystem>
#include <optional>
#include <string>
#include <string_view>

namespace mdk {

// Persisted frontend settings — the proven table entries:
// DAT_00541308 SoundFX (sound row-0 domain [0,100] step 10,
// factory 70), DAT_0054130c SoundMusic (row-1, factory 100),
// DAT_0054147a skill (domain [0,2], factory 1 = "Skill - Normal"),
// DAT_0054147e brightness (display row-0 domain [0,7], factory 0),
// DAT_00541482 ForcePCorrect (type-2 bool, factory FALSE), and the
// Phase-4J Mouse block (entries 49-68 — see the header comment).
// Field order below keeps the 4G/4H members first so existing
// positional `FrontendSettings{skill}` initializers keep their
// meaning; the SERIALIZER emits in original table order (SoundFX,
// SoundMusic, the 49-68 Mouse block, Skill, Brightness,
// ForcePCorrect).
//
// Mouse field shapes (OBSERVED storage): the axis-map and
// button-map keys are type-3 string buffers; the ButtMapA..D keys
// are type-0 dword slots stored as raw bits (BUILD_A writes
// `MouseWButtMapD = 32768`); the scales are type-1 floats;
// MouseOn is type-2; MouseYReversed is a type-1 float slot the
// screen writes raw int32 0/1 into — the port keeps the raw dword
// bits so both file forms (`= 1.4013e-45` after a toggle, `= 1`
// if the user edits by hand) round-trip through the original
// atof read.
struct FrontendSettings {
  int skill = 1;
  int brightness = 0;
  bool forcePCorrect = false;
  int soundFx = 70;
  int soundMusic = 100;
  std::string mouseWAxesMap = "ABG";
  std::string mouseDAxesMap = "ABG";
  std::string mouseWButtMap = "ACB";
  std::string mouseDButtMap = "ACB";
  std::uint32_t mouseWButtMapA = 1;
  std::uint32_t mouseWButtMapB = 4;
  std::uint32_t mouseWButtMapC = 2;
  std::uint32_t mouseWButtMapD = 0;
  std::uint32_t mouseDButtMapA = 1;
  std::uint32_t mouseDButtMapB = 4;
  std::uint32_t mouseDButtMapC = 2;
  std::uint32_t mouseDButtMapD = 0;
  float mouseWXScale = 16.0f;
  float mouseWYScale = 16.0f;
  float mouseWZScale = 50.0f;
  float mouseDXScale = 16.0f;
  float mouseDYScale = 16.0f;
  float mouseDZScale = 50.0f;
  bool mouseOn = true;
  std::uint32_t mouseYReversed = 0;
  // Phase-4K Keyboard block (entries 69-87, type-0 dword slots) —
  // ORIGINAL internal key codes 0..127, factory values from the
  // 0x49b1f2 mirror. 'A'(30)/'Z'(44) legitimately bind two actions
  // each (LookUp+ZoomIn, LookDown+ZoomOut — OBSERVED factory dup).
  int keyLeft = 105;      // 69  UP-arrow extended code 0x69
  int keyRight = 106;     // 70  0x6a
  int keyUp = 103;        // 71  0x67
  int keyDown = 108;      // 72  0x6c
  int keyJump = 56;       // 73  LALT 0x38
  int keySide = 45;       // 74  'X' 0x2d
  int keyFire = 29;       // 75  LCTRL 0x1d
  int keySniper = 57;     // 76  SPACE 0x39
  int keyTurbo = 42;      // 77  LSHIFT 0x2a
  int keySturbo = 58;     // 78  CAPS 0x3a
  int keyLookUp = 30;     // 79  'A' 0x1e
  int keyLookDown = 44;   // 80  'Z' 0x2c
  int keyZoomIn = 30;     // 81  'A' (factory dup of LookUp)
  int keyZoomOut = 44;    // 82  'Z' (factory dup of LookDown)
  int keyItemNext = 27;   // 83  ']' 0x1b
  int keyItemPrev = 26;   // 84  '[' 0x1a
  int keyItemUse = 28;    // 85  RETURN 0x1c
  int keySideL = 51;      // 86  ',' 0x33
  int keySideR = 52;      // 87  '.' 0x34
};

// OBSERVED domain for a Key* type-0 slot: internal codes 0..127.
inline constexpr int kFrontendKeyCodeMax = 127;

inline constexpr int kFrontendSkillDefault = 1;       // @0x49b26e
inline constexpr int kFrontendSkillMin = 0;           // OBSERVED domain
inline constexpr int kFrontendSkillMax = 2;           //   0..2
inline constexpr int kFrontendBrightnessDefault = 0;  // @0x49b272
inline constexpr int kFrontendBrightnessMin = 0;      // OBSERVED row-0
inline constexpr int kFrontendBrightnessMax = 7;      //   domain 0..7
inline constexpr int kFrontendSoundFxDefault = 70;    // @0x49b0fc
inline constexpr int kFrontendSoundMusicDefault = 100;// @0x49b100
inline constexpr int kFrontendSoundVolumeMin = 0;     // OBSERVED rows
inline constexpr int kFrontendSoundVolumeMax = 100;   //   0..100
// Mouse factories — entries 49-68 mirror bytes (@0x49b1ba..):
inline constexpr std::string_view kFrontendMouseAxesMapDefault = "ABG";
inline constexpr std::string_view kFrontendMouseButtMapDefault = "ACB";
inline constexpr std::uint32_t kFrontendMouseButtDefaults[4] =
    {1, 4, 2, 0};
inline constexpr float kFrontendMouseXYScaleDefault = 16.0f;
inline constexpr float kFrontendMouseZScaleDefault = 50.0f;

// OBSERVED file head (`;` comment line + blank line, "\n\n" in the
// original's text-mode write -> CRLF pairs on disk in BUILD_A).
// Reproduced verbatim as the proven format marker — the file stays
// a well-formed MDK.CFG for the future full-table writer.
inline constexpr std::string_view kFrontendSettingsHeader =
    "; MDK Configuration file automatically generated by MDK";

// FUN_004260ac's emission contract for the proven entries
// (OBSERVED): header + blank line, then non-default values in
// table order — `SoundFX = %d` iff != 70, `SoundMusic = %d` iff
// != 100, the entries-49-68 Mouse block iff each differs from its
// mirror (strings fold-compared via FUN_0042fab4 — OBSERVED, so
// "abg" counts as the "ABG" default and is NOT emitted; ints as
// signed `%d`; floats as `%g`; `MouseOn = FALSE` when off), then
// `Skill = %d` iff != 1, `Brightness = %d` iff != 0,
// `ForcePCorrect = TRUE` iff != FALSE (the writer emits a value
// only when the live dword differs from the mirror, so FALSE is
// never emitted for the proven bool). Lines terminate CRLF —
// BUILD_A's on-disk MDK.CFG is a DOS text file; matching its line
// endings keeps written files byte-true to the proven format
// rather than host-dependent.
std::string serializeFrontendSettings(const FrontendSettings& s);

// FUN_00425de4's load contract for the proven entries:
// start from the factory defaults, apply `name = value` lines in
// order (the last valid line for each key wins). `;`-led lines
// and lines without a valid `name = value` shape are skipped like
// the original's parser.
//
// NATIVE POLICY — hardening, NOT an original-behavior claim: a
// `Skill`/`Brightness`/`SoundFX`/`SoundMusic` line whose value
// fails integer parse or falls outside the proven domain
// ([0,2] / [0,7] / [0,100]) is ignored (the running value is
// kept) and counted. The original stores whatever its strtol-style
// parse yields — that edge behavior is UNKNOWN and deliberately
// not reproduced. `ForcePCorrect` is type 2: the original applies
// it unconditionally as toupper(first value char) == 'T'
// (FUN_0047d1a5 + `cmp 0x54`) — reproduced exactly, never
// counted as ignored.
//
// Phase-4J Mouse block (OBSERVED per-type reads): type-3 map
// strings are copied verbatim (NATIVE hardening: bounded — the
// original's strcpy into fixed buffers is unbounded, UNKNOWN at
// the overflow edge and deliberately not reproduced); type-0
// ButtMapA..D parse a leading int stored as raw bits; type-1
// scales parse a leading float (atof-family); `MouseOn` is type-2
// (`T`-first-char, unconditional); `MouseYReversed` reads the
// float slot so BOTH file forms round-trip — `1` (int-looking
// hand edit) parses to float 1.0f, `1.4013e-45` parses to the
// denormal; a failed scale/mask parse is ignored and counted in
// `ignoredMouseLines` (NATIVE hardening).
//
// Phase-4K Keyboard block (OBSERVED type-0 read): the 19 Key* lines
// parse a leading int into the internal-code slot. NATIVE
// hardening: failed parse or a value outside the proven 0..127
// domain is ignored and counted in `ignoredKeyLines` (the
// original's strtol-store edge is UNKNOWN, not reproduced).
struct FrontendSettingsParse {
  FrontendSettings settings;
  int ignoredSkillLines = 0;
  int ignoredBrightnessLines = 0;
  int ignoredSoundFxLines = 0;
  int ignoredSoundMusicLines = 0;
  int ignoredMouseLines = 0;
  int ignoredKeyLines = 0;
};
FrontendSettingsParse parseFrontendSettings(std::string_view text);

// Native-owned file seam — the only frontend-settings I/O in the
// port. `path` is always caller-supplied and must live OUTSIDE the
// read-only DataRoot (enforced by the caller/app layer — this
// module holds no data-root reference at all).
//
// load: nullopt when the file is absent (fresh-boot case — not an
// error); fills `err` and returns nullopt on a real read failure.
// save: false + `err` on any open/write failure — the caller
// decides the failure policy (the flow mirrors the original's
// unconditional dirty-flag clear even on write failure).
std::optional<FrontendSettingsParse> loadFrontendSettingsFile(
    const std::filesystem::path& path, std::string* err = nullptr);
bool saveFrontendSettingsFile(const std::filesystem::path& path,
                              const FrontendSettings& s,
                              std::string* err = nullptr);

} // namespace mdk

#endif // MDK_CORE_FRONTEND_SETTINGS_H
